### ISSUE TITLE
Not packaged for Windows

### ISSUE THREAD

**Issue by bilderbuchi** [conda-forge/fpm-feedstock#4]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
Apparently, fpm is not packaged for Windows on conda-forge
```
>conda search fpm
Loading channels: done
No match found for: fpm. Search: *fpm*
# Name                       Version           Build  Channel
r-leafpm                       0.1.0  r351h6115d3f_0  conda-forge

```
r-leafpm is another unrelated package.
This is on Windows 10, conda 4.10.1
This is confirmed by the "platforms" badge in your Readme, which only mention linux and osx.

Is a Windows build going to be available via conda? I noticed that Windows binaries are being published, so there does not seem to be a technical hurdle?

**Comment by awvwgk** [comment]
It actually is a technical issue, because we don't have a sufficiently new compiler available to actually build on Windows using the conda-forge toolchain.

Related discussion at the fpm repository: https://github.com/fortran-lang/fpm/discussions/393
Related comment at staged-recipes: https://github.com/conda-forge/staged-recipes/pull/14269#issuecomment-800395528

Alternatives (outside of conda-forge) are currently the statically linked binaries from the fpm release page or the MinGW packages at https://github.com/awvwgk/mingw-w64-fpm-pkgbuild.

**Comment by bilderbuchi** [comment]
Oh, thank you for clarifying, and linking to the wider discussion! Let's hope that there is some progress on the conda compiler landscape. 
I think it's great that you are using conda to distribute fpm, it's not often that I see people using condas multi-language capabilities. 

(I'm coming from the python world here, and I have to admit I did not miss messing around with build configuration/tool compatibilities one bit)

**Comment by certik** [comment]
Thanks @bilderbuchi for reporting this. Let's keep this issue open until we fix it.

**Comment by bilderbuchi** [comment]
I'm wondering, now that lfortran MVP is out (congrats!), how much is missing to compile fpm with lfortran instead of the old gcc? That could maybe be the fastest way to get fpm packaged for Windows?

**Comment by awvwgk** [comment]
There is an issue at the LFortran repository for this and I commented on there on the required first steps as well: [lfortran#539](https://gitlab.com/lfortran/lfortran/-/issues/539).

**Comment by certik** [comment]
@bilderbuchi in the next few weeks I'll focus on a `--symtab-only` mode and try to get `fpm` to compile with that (https://gitlab.com/lfortran/lfortran/-/issues/592). In this mode all the semantics gets done for everything except executable statements, it still produces a valid ASR (just with empty function bodies). I think we might be really close, I spent a few hours yesterday and got `fpm_strings.f90` almost compiling in this mode (just one more tiny fix I still have to do). So this will be the first milestone once the whole `fpm` compiles in this mode.

After that, I'll focus on the executable statements. 

Regarding the `link` on Windows --- that is the default MSVC linker. You can also use mingw, LFortran works with it too. You need some C compiler for `fpm` anyway. So whichever C compiler you use, we can use their linker. We can also finish this MR, which uses LLVM's LLD for linking: https://gitlab.com/lfortran/lfortran/-/merge_requests/413, then it should be able to link on its own, no external dependency. We test LFortran on Windows at our CI, so at least it works in some way (with MSVC), and I know people can help us making it working with other toolchains; so I am focusing on the actual compilation, that's where my time is best spent.

Let's put it this way: if LFortran can compile `fpm` by Christmas, it would be a nice Christmas gift for me.

**Comment by bilderbuchi** [comment]
Thanks for the context, no pressure from my side!
@link: right. I don't have msvc installed, but a gcc (and llvm, too), so I was surprised that default settings did not pick that up. 
I should have checked if there is some command line flag or somesuch that would have helped, and I'll have to confirm that my environment really was in order.

**Comment by certik** [comment]
If you have `mingw`, you can try `lfortran --target=x86_64-w64-windows-gnu` for mingw, that will use `gcc` to link (the default is `x86_64-pc-windows-msvc` for MSVC).

**Comment by bilderbuchi** [comment]
I noticed that this is available now, thank you! Installation worked and fpm seems to work. 🥳 
Now I need to find the time to take this for a spin (the project I originally intended to use this with is by now oriented around cmake for building and pytest+f2py for testing).
